config/routes.rb
Rails.application.routes.draw do

	get '/users/getaddress', to: 'users#findAddress'
	get '/drivers/changecurrentstatus', to: 'drivers#changeCurrentStatus'
	get '/drivers/checkForRideRequests', to: 'drivers#checkForRideRequests'
	get '/drivers/acceptrequest', to: 'drivers#acceptRequest'
	get '/drivers/reset', to: 'drivers#reset'
	get '/drivers/getdirections', to: 'drivers#getDirections'
	get '/drivers/logTripCoordinates', to: 'drivers#logTripCoordinates'
	get '/drivers/getsnappedcoordinates', to: 'drivers#getSnappedCoordinates'


	resources :users do 
		resources :trip_requests
		resources :active_trips
		resources :completed_trips
	end

	resources :drivers do
		resources :active_trips
		resources :completed_trips
	end

	resources :active_trips

  	root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/forms/_ride-from-hotel-form.html.erb
<%= form_for :trip, :url => trips_path, :remote => true, html: { :id => 'create_new_trip' } do |f| %>
  <div class="form-group">
    <%= f.select(:destination, options_for_select([["Select Your Destination",""],["JFK","JFK"],["LaGuardia","LaGuardia"],["Newark","Newark"]]), {}, class: "custom-select form-control") %>
    <div class="form-group position-relative">
      <%= f.label :number_passengers, "How Many Passengers?", class: "control-label-hide", id: "nickNameLabel" %>
      <%= f.text_field :number_passengers, { id: "nickname-input", class: "form-control", type: "text", placeholder: "How Many Passengers?" } %>
    </div>
    <div class="form-group position-relative">
      <%= f.label :number_luggage, "How much Luggage?", class: "control-label-hide", id: "nickNameLabel" %>
      <%= f.text_field :number_luggage, { id: "nickname-input", class: "form-control", type: "text", placeholder: "How much Luggage?" } %>
    </div>
  </div>
  <%= f.submit 'trip', { value: "Submit", id: "submitTrip", class: "btn btn-lg btn-success" }%>
<% end %>

app/views/forms/_sign-up-form.html.erb
<div class="sign-up" id="sign-up-form">
  <%= form_for :user, :url => users_path, :remote => true, html: { :id => 'create_new_user' } do |f| %>
    <div class="form-group">
    <%= f.select(:hotel_name, options_for_select([["Select Your Hotel",""],["Marriott","Marriott"],["Sheraton","Sheraton"],["Hilton","Hilton"],["Hyatt Regency","Hyatt Regency"],["Crowne Plaza","Crowne Plaza"],["Holiday Inn","Holiday Inn"]]), {}, class: "custom-select form-control") %>
    </div>
    <div class="form-group position-relative">
      <%= f.label :nickname, "Choose A Nickname", class: "control-label-hide", id: "nickNameLabel" %>
      <%= f.text_field :nickname, { id: "nickname-input", class: "form-control", type: "text", placeholder: "Choose A Nickname" } %>
    </div>
    <button type="button" class="btn btn-block btn-lg btn-primary" data-toggle="modal" data-target="#iconsModal" id="select-icon-btn">Select An Icon</button>
    <div id="show-user-icon">
      <div class="row flexcontainer-row">
        <div class="col-sm-3">
          <span id="user-icon"></span>
        </div>
      <div class="col-sm-9">
        <button type="button" class="btn btn-block btn-lg btn-primary" data-toggle="modal" data-target="#iconsModal" id="select-icon-btn">Choose A New Icon</button>
      </div>
      </div>
    </div>
    <br>
    <br>
    <br>
    <%= f.submit 'user', { value: "Submit", id: "submitUser", class: "btn btn-block btn-lg btn-success" }%>
  <% end %>
</div>